// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: leochain/blt/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the x/blt module.
type Params struct {
	ClusterCount             uint32 `protobuf:"varint,1,opt,name=cluster_count,json=clusterCount,proto3" json:"cluster_count,omitempty"`
	EpochLengthMs            uint32 `protobuf:"varint,2,opt,name=epoch_length_ms,json=epochLengthMs,proto3" json:"epoch_length_ms,omitempty"`
	MaxMemberRecordsPerBlock uint64 `protobuf:"varint,3,opt,name=max_member_records_per_block,json=maxMemberRecordsPerBlock,proto3" json:"max_member_records_per_block,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d5927c03ecdd094, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetClusterCount() uint32 {
	if m != nil {
		return m.ClusterCount
	}
	return 0
}

func (m *Params) GetEpochLengthMs() uint32 {
	if m != nil {
		return m.EpochLengthMs
	}
	return 0
}

func (m *Params) GetMaxMemberRecordsPerBlock() uint64 {
	if m != nil {
		return m.MaxMemberRecordsPerBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "leochain.blt.Params")
}

func init() { proto.RegisterFile("leochain/blt/params.proto", fileDescriptor_1d5927c03ecdd094) }

var fileDescriptor_1d5927c03ecdd094 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0x49, 0xcd, 0x4f,
	0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0xca, 0x29, 0xd1, 0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x81, 0x49, 0xe9, 0x25, 0xe5, 0x94, 0x48, 0x09, 0x26,
	0xe6, 0x66, 0xe6, 0xe5, 0xeb, 0x83, 0x49, 0x88, 0x02, 0x29, 0x91, 0xf4, 0xfc, 0xf4, 0x7c, 0x30,
	0x53, 0x1f, 0xc4, 0x82, 0x88, 0x2a, 0x6d, 0x65, 0xe4, 0x62, 0x0b, 0x00, 0x9b, 0x23, 0xa4, 0xcc,
	0xc5, 0x9b, 0x9c, 0x53, 0x5a, 0x5c, 0x92, 0x5a, 0x14, 0x9f, 0x9c, 0x5f, 0x9a, 0x57, 0x22, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x1b, 0xc4, 0x03, 0x15, 0x74, 0x06, 0x89, 0x09, 0xa9, 0x71, 0xf1, 0xa7,
	0x16, 0xe4, 0x27, 0x67, 0xc4, 0xe7, 0xa4, 0xe6, 0xa5, 0x97, 0x64, 0xc4, 0xe7, 0x16, 0x4b, 0x30,
	0x81, 0x95, 0xf1, 0x82, 0x85, 0x7d, 0xc0, 0xa2, 0xbe, 0xc5, 0x42, 0x76, 0x5c, 0x32, 0xb9, 0x89,
	0x15, 0xf1, 0xb9, 0xa9, 0xb9, 0x49, 0xa9, 0x45, 0xf1, 0x45, 0xa9, 0xc9, 0xf9, 0x45, 0x29, 0xc5,
	0xf1, 0x05, 0xa9, 0x45, 0xf1, 0x49, 0x39, 0xf9, 0xc9, 0xd9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x2c,
	0x41, 0x12, 0xb9, 0x89, 0x15, 0xbe, 0x60, 0x25, 0x41, 0x10, 0x15, 0x01, 0xa9, 0x45, 0x4e, 0x20,
	0x79, 0x2b, 0xb9, 0x17, 0x0b, 0xe4, 0x19, 0xbb, 0x9e, 0x6f, 0xd0, 0x12, 0x85, 0x7b, 0xb9, 0x02,
	0xec, 0x69, 0x88, 0x63, 0x9d, 0xf4, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1,
	0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21,
	0x4a, 0x04, 0x4d, 0x43, 0x49, 0x65, 0x41, 0x6a, 0x71, 0x12, 0x1b, 0xd8, 0xbb, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x38, 0xfb, 0x65, 0xad, 0x42, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ClusterCount != that1.ClusterCount {
		return false
	}
	if this.EpochLengthMs != that1.EpochLengthMs {
		return false
	}
	if this.MaxMemberRecordsPerBlock != that1.MaxMemberRecordsPerBlock {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxMemberRecordsPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxMemberRecordsPerBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.EpochLengthMs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochLengthMs))
		i--
		dAtA[i] = 0x10
	}
	if m.ClusterCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ClusterCount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterCount != 0 {
		n += 1 + sovParams(uint64(m.ClusterCount))
	}
	if m.EpochLengthMs != 0 {
		n += 1 + sovParams(uint64(m.EpochLengthMs))
	}
	if m.MaxMemberRecordsPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxMemberRecordsPerBlock))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterCount", wireType)
			}
			m.ClusterCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLengthMs", wireType)
			}
			m.EpochLengthMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLengthMs |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMemberRecordsPerBlock", wireType)
			}
			m.MaxMemberRecordsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMemberRecordsPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
