// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: leochain/blt/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_394c3f2dbb3e94cb, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_394c3f2dbb3e94cb, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryLatestEpochRequest struct {
}

func (m *QueryLatestEpochRequest) Reset()         { *m = QueryLatestEpochRequest{} }
func (m *QueryLatestEpochRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLatestEpochRequest) ProtoMessage()    {}
func (*QueryLatestEpochRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_394c3f2dbb3e94cb, []int{2}
}
func (m *QueryLatestEpochRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestEpochRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestEpochRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestEpochRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestEpochRequest.Merge(m, src)
}
func (m *QueryLatestEpochRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestEpochRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestEpochRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestEpochRequest proto.InternalMessageInfo

type QueryLatestEpochResponse struct {
	Snapshot BltEpochSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot"`
}

func (m *QueryLatestEpochResponse) Reset()         { *m = QueryLatestEpochResponse{} }
func (m *QueryLatestEpochResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLatestEpochResponse) ProtoMessage()    {}
func (*QueryLatestEpochResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_394c3f2dbb3e94cb, []int{3}
}
func (m *QueryLatestEpochResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestEpochResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestEpochResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestEpochResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestEpochResponse.Merge(m, src)
}
func (m *QueryLatestEpochResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestEpochResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestEpochResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestEpochResponse proto.InternalMessageInfo

func (m *QueryLatestEpochResponse) GetSnapshot() BltEpochSnapshot {
	if m != nil {
		return m.Snapshot
	}
	return BltEpochSnapshot{}
}

type QueryEpochHistoryRequest struct {
	EpochId uint32 `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
}

func (m *QueryEpochHistoryRequest) Reset()         { *m = QueryEpochHistoryRequest{} }
func (m *QueryEpochHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEpochHistoryRequest) ProtoMessage()    {}
func (*QueryEpochHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_394c3f2dbb3e94cb, []int{4}
}
func (m *QueryEpochHistoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochHistoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochHistoryRequest.Merge(m, src)
}
func (m *QueryEpochHistoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochHistoryRequest proto.InternalMessageInfo

func (m *QueryEpochHistoryRequest) GetEpochId() uint32 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

type QueryEpochHistoryResponse struct {
	Snapshot BltEpochSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot"`
}

func (m *QueryEpochHistoryResponse) Reset()         { *m = QueryEpochHistoryResponse{} }
func (m *QueryEpochHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEpochHistoryResponse) ProtoMessage()    {}
func (*QueryEpochHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_394c3f2dbb3e94cb, []int{5}
}
func (m *QueryEpochHistoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochHistoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochHistoryResponse.Merge(m, src)
}
func (m *QueryEpochHistoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochHistoryResponse proto.InternalMessageInfo

func (m *QueryEpochHistoryResponse) GetSnapshot() BltEpochSnapshot {
	if m != nil {
		return m.Snapshot
	}
	return BltEpochSnapshot{}
}

type QueryDelegateSetRequest struct {
}

func (m *QueryDelegateSetRequest) Reset()         { *m = QueryDelegateSetRequest{} }
func (m *QueryDelegateSetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDelegateSetRequest) ProtoMessage()    {}
func (*QueryDelegateSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_394c3f2dbb3e94cb, []int{6}
}
func (m *QueryDelegateSetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDelegateSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDelegateSetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDelegateSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDelegateSetRequest.Merge(m, src)
}
func (m *QueryDelegateSetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDelegateSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDelegateSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDelegateSetRequest proto.InternalMessageInfo

type QueryDelegateSetResponse struct {
	DelegateSet BltDelegateSet `protobuf:"bytes,1,opt,name=delegate_set,json=delegateSet,proto3" json:"delegate_set"`
}

func (m *QueryDelegateSetResponse) Reset()         { *m = QueryDelegateSetResponse{} }
func (m *QueryDelegateSetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDelegateSetResponse) ProtoMessage()    {}
func (*QueryDelegateSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_394c3f2dbb3e94cb, []int{7}
}
func (m *QueryDelegateSetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDelegateSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDelegateSetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDelegateSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDelegateSetResponse.Merge(m, src)
}
func (m *QueryDelegateSetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDelegateSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDelegateSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDelegateSetResponse proto.InternalMessageInfo

func (m *QueryDelegateSetResponse) GetDelegateSet() BltDelegateSet {
	if m != nil {
		return m.DelegateSet
	}
	return BltDelegateSet{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "leochain.blt.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "leochain.blt.QueryParamsResponse")
	proto.RegisterType((*QueryLatestEpochRequest)(nil), "leochain.blt.QueryLatestEpochRequest")
	proto.RegisterType((*QueryLatestEpochResponse)(nil), "leochain.blt.QueryLatestEpochResponse")
	proto.RegisterType((*QueryEpochHistoryRequest)(nil), "leochain.blt.QueryEpochHistoryRequest")
	proto.RegisterType((*QueryEpochHistoryResponse)(nil), "leochain.blt.QueryEpochHistoryResponse")
	proto.RegisterType((*QueryDelegateSetRequest)(nil), "leochain.blt.QueryDelegateSetRequest")
	proto.RegisterType((*QueryDelegateSetResponse)(nil), "leochain.blt.QueryDelegateSetResponse")
}

func init() { proto.RegisterFile("leochain/blt/query.proto", fileDescriptor_394c3f2dbb3e94cb) }

var fileDescriptor_394c3f2dbb3e94cb = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0x6e, 0x64, 0xad, 0xeb, 0xb4, 0x1e, 0x1c, 0x83, 0xb6, 0xa1, 0xc4, 0x35, 0xe0, 0xba, 0xec,
	0x21, 0xc3, 0xae, 0x88, 0x57, 0x29, 0x2e, 0x28, 0x88, 0x68, 0xf7, 0x26, 0x4a, 0x99, 0xb4, 0x43,
	0x1a, 0x4c, 0xf3, 0xb2, 0x9d, 0x59, 0xb1, 0x88, 0x20, 0x9e, 0x05, 0x05, 0xff, 0x84, 0x47, 0x7f,
	0xc6, 0x1e, 0x17, 0xbc, 0x78, 0x12, 0x69, 0x05, 0xff, 0x86, 0x74, 0xe6, 0x65, 0x37, 0x21, 0xa3,
	0x7b, 0xf1, 0x52, 0xd2, 0xf7, 0xbe, 0xf7, 0x7d, 0x5f, 0xde, 0xfb, 0x08, 0xe9, 0xa4, 0x02, 0x46,
	0x13, 0x9e, 0x64, 0x2c, 0x4a, 0x15, 0x3b, 0x38, 0x14, 0xb3, 0x79, 0x98, 0xcf, 0x40, 0x01, 0x6d,
	0x17, 0x9d, 0x30, 0x4a, 0x95, 0x77, 0x99, 0x4f, 0x93, 0x0c, 0x98, 0xfe, 0x35, 0x00, 0xcf, 0x8d,
	0x21, 0x06, 0xfd, 0xc8, 0x56, 0x4f, 0x58, 0xed, 0xc5, 0x00, 0x71, 0x2a, 0x18, 0xcf, 0x13, 0xc6,
	0xb3, 0x0c, 0x14, 0x57, 0x09, 0x64, 0x12, 0xbb, 0xdb, 0x23, 0x90, 0x53, 0x90, 0x2c, 0xe2, 0x52,
	0x18, 0x35, 0xf6, 0x6a, 0x27, 0x12, 0x8a, 0xef, 0xb0, 0x9c, 0xc7, 0x49, 0xa6, 0xc1, 0x88, 0xed,
	0x56, 0xac, 0xe5, 0x7c, 0xc6, 0xa7, 0x05, 0x4d, 0xd5, 0xb5, 0x9a, 0xe7, 0x02, 0x3b, 0x81, 0x4b,
	0xe8, 0xd3, 0x15, 0xed, 0x13, 0x0d, 0x1f, 0x88, 0x83, 0x43, 0x21, 0x55, 0xf0, 0x98, 0x5c, 0xa9,
	0x54, 0x65, 0x0e, 0x99, 0x14, 0xf4, 0x2e, 0x69, 0x1a, 0xda, 0x8e, 0xb3, 0xe1, 0x6c, 0xb5, 0x76,
	0xdd, 0xb0, 0xfc, 0xce, 0xa1, 0x41, 0xf7, 0x2f, 0x1e, 0xfd, 0xb8, 0xde, 0xf8, 0xf2, 0xfb, 0xeb,
	0xb6, 0x33, 0x40, 0x78, 0xd0, 0x25, 0xd7, 0x34, 0xdf, 0x23, 0xae, 0x84, 0x54, 0x7b, 0x39, 0x8c,
	0x26, 0x85, 0xd4, 0x73, 0xd2, 0xa9, 0xb7, 0x50, 0xef, 0x1e, 0x59, 0x97, 0x19, 0xcf, 0xe5, 0x04,
	0x14, 0x2a, 0xfa, 0x55, 0xc5, 0x7e, 0x6a, 0x26, 0xf6, 0x11, 0xd5, 0x5f, 0x5b, 0x69, 0x0f, 0x4e,
	0xa6, 0x82, 0x3b, 0xc8, 0xae, 0x51, 0x0f, 0x12, 0xa9, 0x60, 0x36, 0x47, 0x65, 0xda, 0x25, 0xeb,
	0x62, 0x55, 0x1e, 0x26, 0x63, 0xcd, 0x7e, 0x69, 0x70, 0x41, 0xff, 0x7f, 0x38, 0x0e, 0x5e, 0x90,
	0xae, 0x65, 0xec, 0xbf, 0xb9, 0x2a, 0xd6, 0x71, 0x5f, 0xa4, 0x22, 0xe6, 0x4a, 0xec, 0x0b, 0x55,
	0xac, 0x83, 0xa3, 0xe1, 0x4a, 0x0b, 0x85, 0xf7, 0x48, 0x7b, 0x8c, 0xe5, 0xa1, 0x14, 0x85, 0x78,
	0xaf, 0x26, 0x5e, 0x9a, 0x45, 0xe9, 0xd6, 0xf8, 0xb4, 0xb4, 0xfb, 0x61, 0x8d, 0x9c, 0xd7, 0x1a,
	0xf4, 0x25, 0x69, 0x9a, 0x9b, 0xd1, 0x8d, 0x2a, 0x49, 0x3d, 0x12, 0xde, 0x8d, 0x7f, 0x20, 0x8c,
	0xbf, 0xa0, 0xf7, 0xfe, 0xdb, 0xaf, 0xcf, 0xe7, 0xae, 0x52, 0x97, 0x59, 0x92, 0x48, 0xdf, 0x39,
	0xa4, 0x55, 0x3a, 0x32, 0xbd, 0x69, 0x21, 0xac, 0xe7, 0xc3, 0xdb, 0x3c, 0x0b, 0x86, 0xe2, 0x81,
	0x16, 0xef, 0x51, 0xaf, 0x2a, 0x9e, 0x6a, 0xe8, 0x50, 0x1f, 0x96, 0x7e, 0x74, 0x48, 0xbb, 0x7c,
	0x52, 0x6a, 0x23, 0xb7, 0x44, 0xc5, 0xbb, 0x75, 0x26, 0x0e, 0x5d, 0x84, 0xda, 0xc5, 0x16, 0xdd,
	0xac, 0xba, 0x30, 0x39, 0x9b, 0x18, 0x30, 0x7b, 0x53, 0xc4, 0xee, 0xad, 0x5e, 0x4a, 0xe9, 0x5c,
	0xd6, 0xa5, 0xd4, 0x53, 0x62, 0x5d, 0x8a, 0x25, 0x31, 0x7f, 0x5b, 0x4a, 0x39, 0x45, 0xfd, 0xf0,
	0x68, 0xe1, 0x3b, 0xc7, 0x0b, 0xdf, 0xf9, 0xb9, 0xf0, 0x9d, 0x4f, 0x4b, 0xbf, 0x71, 0xbc, 0xf4,
	0x1b, 0xdf, 0x97, 0x7e, 0xe3, 0x99, 0x7b, 0x32, 0xf4, 0xfa, 0xf4, 0xbb, 0x11, 0x35, 0xf5, 0x87,
	0xe3, 0xf6, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xca, 0x88, 0xed, 0x0a, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// LatestEpoch returns the most recently finalized BltEpochSnapshot.
	LatestEpoch(ctx context.Context, in *QueryLatestEpochRequest, opts ...grpc.CallOption) (*QueryLatestEpochResponse, error)
	// EpochHistory returns a single past epoch snapshot by id.
	EpochHistory(ctx context.Context, in *QueryEpochHistoryRequest, opts ...grpc.CallOption) (*QueryEpochHistoryResponse, error)
	// DelegateSet returns the active 12 cluster-head delegates.
	DelegateSet(ctx context.Context, in *QueryDelegateSetRequest, opts ...grpc.CallOption) (*QueryDelegateSetResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/leochain.blt.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestEpoch(ctx context.Context, in *QueryLatestEpochRequest, opts ...grpc.CallOption) (*QueryLatestEpochResponse, error) {
	out := new(QueryLatestEpochResponse)
	err := c.cc.Invoke(ctx, "/leochain.blt.Query/LatestEpoch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EpochHistory(ctx context.Context, in *QueryEpochHistoryRequest, opts ...grpc.CallOption) (*QueryEpochHistoryResponse, error) {
	out := new(QueryEpochHistoryResponse)
	err := c.cc.Invoke(ctx, "/leochain.blt.Query/EpochHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DelegateSet(ctx context.Context, in *QueryDelegateSetRequest, opts ...grpc.CallOption) (*QueryDelegateSetResponse, error) {
	out := new(QueryDelegateSetResponse)
	err := c.cc.Invoke(ctx, "/leochain.blt.Query/DelegateSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// LatestEpoch returns the most recently finalized BltEpochSnapshot.
	LatestEpoch(context.Context, *QueryLatestEpochRequest) (*QueryLatestEpochResponse, error)
	// EpochHistory returns a single past epoch snapshot by id.
	EpochHistory(context.Context, *QueryEpochHistoryRequest) (*QueryEpochHistoryResponse, error)
	// DelegateSet returns the active 12 cluster-head delegates.
	DelegateSet(context.Context, *QueryDelegateSetRequest) (*QueryDelegateSetResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) LatestEpoch(ctx context.Context, req *QueryLatestEpochRequest) (*QueryLatestEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestEpoch not implemented")
}
func (*UnimplementedQueryServer) EpochHistory(ctx context.Context, req *QueryEpochHistoryRequest) (*QueryEpochHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochHistory not implemented")
}
func (*UnimplementedQueryServer) DelegateSet(ctx context.Context, req *QueryDelegateSetRequest) (*QueryDelegateSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegateSet not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leochain.blt.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leochain.blt.Query/LatestEpoch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestEpoch(ctx, req.(*QueryLatestEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EpochHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEpochHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EpochHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leochain.blt.Query/EpochHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EpochHistory(ctx, req.(*QueryEpochHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DelegateSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDelegateSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DelegateSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leochain.blt.Query/DelegateSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DelegateSet(ctx, req.(*QueryDelegateSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "leochain.blt.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "LatestEpoch",
			Handler:    _Query_LatestEpoch_Handler,
		},
		{
			MethodName: "EpochHistory",
			Handler:    _Query_EpochHistory_Handler,
		},
		{
			MethodName: "DelegateSet",
			Handler:    _Query_DelegateSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leochain/blt/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryLatestEpochRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestEpochRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestEpochRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLatestEpochResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestEpochResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestEpochResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Snapshot.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryEpochHistoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochHistoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochHistoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryEpochHistoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochHistoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochHistoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Snapshot.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryDelegateSetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDelegateSetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDelegateSetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDelegateSetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDelegateSetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDelegateSetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DelegateSet.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLatestEpochRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLatestEpochResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Snapshot.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryEpochHistoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochId != 0 {
		n += 1 + sovQuery(uint64(m.EpochId))
	}
	return n
}

func (m *QueryEpochHistoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Snapshot.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDelegateSetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDelegateSetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DelegateSet.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestEpochRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestEpochRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestEpochRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestEpochResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestEpochResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestEpochResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Snapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochHistoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochHistoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochHistoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochId", wireType)
			}
			m.EpochId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochHistoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochHistoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochHistoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Snapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDelegateSetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDelegateSetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDelegateSetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDelegateSetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDelegateSetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDelegateSetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegateSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegateSet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
