// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: leochain/blt/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BltBodyGlobal carries the global synchronization view that the block
// proposer asserts for this epoch. All time fields are encoded in 0.1 ns
// units (q01ns) per BLT-SAND spec.
type BltBodyGlobal struct {
	GlobalRefTimeQ01Ns uint64 `protobuf:"varint,1,opt,name=global_ref_time_q01ns,json=globalRefTimeQ01ns,proto3" json:"global_ref_time_q01ns,omitempty"`
	ClusterCount       uint32 `protobuf:"varint,2,opt,name=cluster_count,json=clusterCount,proto3" json:"cluster_count,omitempty"`
	MemberCount        uint32 `protobuf:"varint,3,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
}

func (m *BltBodyGlobal) Reset()         { *m = BltBodyGlobal{} }
func (m *BltBodyGlobal) String() string { return proto.CompactTextString(m) }
func (*BltBodyGlobal) ProtoMessage()    {}
func (*BltBodyGlobal) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfaeb864dd5fb412, []int{0}
}
func (m *BltBodyGlobal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BltBodyGlobal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BltBodyGlobal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BltBodyGlobal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BltBodyGlobal.Merge(m, src)
}
func (m *BltBodyGlobal) XXX_Size() int {
	return m.Size()
}
func (m *BltBodyGlobal) XXX_DiscardUnknown() {
	xxx_messageInfo_BltBodyGlobal.DiscardUnknown(m)
}

var xxx_messageInfo_BltBodyGlobal proto.InternalMessageInfo

func (m *BltBodyGlobal) GetGlobalRefTimeQ01Ns() uint64 {
	if m != nil {
		return m.GlobalRefTimeQ01Ns
	}
	return 0
}

func (m *BltBodyGlobal) GetClusterCount() uint32 {
	if m != nil {
		return m.ClusterCount
	}
	return 0
}

func (m *BltBodyGlobal) GetMemberCount() uint32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

// BltClusterSummary is one row per cluster head, summarizing the
// intra-cluster offset distribution and the head's offset to global ref.
type BltClusterSummary struct {
	ClusterId               uint32 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	HeadId                  uint32 `protobuf:"varint,2,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	HeadOffsetToGlobalQ01Ns int32  `protobuf:"zigzag32,3,opt,name=head_offset_to_global_q01ns,json=headOffsetToGlobalQ01ns,proto3" json:"head_offset_to_global_q01ns,omitempty"`
	MemberCount             uint32 `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	InlierCount             uint32 `protobuf:"varint,5,opt,name=inlier_count,json=inlierCount,proto3" json:"inlier_count,omitempty"`
	MemberOffsetMeanQ01Ns   int32  `protobuf:"zigzag32,6,opt,name=member_offset_mean_q01ns,json=memberOffsetMeanQ01ns,proto3" json:"member_offset_mean_q01ns,omitempty"`
	MemberOffsetVarQ01Ns2   uint32 `protobuf:"varint,7,opt,name=member_offset_var_q01ns2,json=memberOffsetVarQ01ns2,proto3" json:"member_offset_var_q01ns2,omitempty"`
}

func (m *BltClusterSummary) Reset()         { *m = BltClusterSummary{} }
func (m *BltClusterSummary) String() string { return proto.CompactTextString(m) }
func (*BltClusterSummary) ProtoMessage()    {}
func (*BltClusterSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfaeb864dd5fb412, []int{1}
}
func (m *BltClusterSummary) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BltClusterSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BltClusterSummary.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BltClusterSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BltClusterSummary.Merge(m, src)
}
func (m *BltClusterSummary) XXX_Size() int {
	return m.Size()
}
func (m *BltClusterSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_BltClusterSummary.DiscardUnknown(m)
}

var xxx_messageInfo_BltClusterSummary proto.InternalMessageInfo

func (m *BltClusterSummary) GetClusterId() uint32 {
	if m != nil {
		return m.ClusterId
	}
	return 0
}

func (m *BltClusterSummary) GetHeadId() uint32 {
	if m != nil {
		return m.HeadId
	}
	return 0
}

func (m *BltClusterSummary) GetHeadOffsetToGlobalQ01Ns() int32 {
	if m != nil {
		return m.HeadOffsetToGlobalQ01Ns
	}
	return 0
}

func (m *BltClusterSummary) GetMemberCount() uint32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

func (m *BltClusterSummary) GetInlierCount() uint32 {
	if m != nil {
		return m.InlierCount
	}
	return 0
}

func (m *BltClusterSummary) GetMemberOffsetMeanQ01Ns() int32 {
	if m != nil {
		return m.MemberOffsetMeanQ01Ns
	}
	return 0
}

func (m *BltClusterSummary) GetMemberOffsetVarQ01Ns2() uint32 {
	if m != nil {
		return m.MemberOffsetVarQ01Ns2
	}
	return 0
}

// BltMemberRecord is one row per member satellite (full record policy).
type BltMemberRecord struct {
	NodeId            uint32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ClusterId         uint32 `protobuf:"varint,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	OffsetToHeadQ01Ns int32  `protobuf:"zigzag32,3,opt,name=offset_to_head_q01ns,json=offsetToHeadQ01ns,proto3" json:"offset_to_head_q01ns,omitempty"`
	RespProbQ255      uint32 `protobuf:"varint,4,opt,name=resp_prob_q255,json=respProbQ255,proto3" json:"resp_prob_q255,omitempty"`
	TimeAccQ01Ns      uint32 `protobuf:"varint,5,opt,name=time_acc_q01ns,json=timeAccQ01ns,proto3" json:"time_acc_q01ns,omitempty"`
	Flags             uint32 `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`
}

func (m *BltMemberRecord) Reset()         { *m = BltMemberRecord{} }
func (m *BltMemberRecord) String() string { return proto.CompactTextString(m) }
func (*BltMemberRecord) ProtoMessage()    {}
func (*BltMemberRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfaeb864dd5fb412, []int{2}
}
func (m *BltMemberRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BltMemberRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BltMemberRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BltMemberRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BltMemberRecord.Merge(m, src)
}
func (m *BltMemberRecord) XXX_Size() int {
	return m.Size()
}
func (m *BltMemberRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_BltMemberRecord.DiscardUnknown(m)
}

var xxx_messageInfo_BltMemberRecord proto.InternalMessageInfo

func (m *BltMemberRecord) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *BltMemberRecord) GetClusterId() uint32 {
	if m != nil {
		return m.ClusterId
	}
	return 0
}

func (m *BltMemberRecord) GetOffsetToHeadQ01Ns() int32 {
	if m != nil {
		return m.OffsetToHeadQ01Ns
	}
	return 0
}

func (m *BltMemberRecord) GetRespProbQ255() uint32 {
	if m != nil {
		return m.RespProbQ255
	}
	return 0
}

func (m *BltMemberRecord) GetTimeAccQ01Ns() uint32 {
	if m != nil {
		return m.TimeAccQ01Ns
	}
	return 0
}

func (m *BltMemberRecord) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

// BltBlockBody bundles the global view, per-cluster summaries and the full
// member table per spec §4.3 (full-record policy).
type BltBlockBody struct {
	Global       BltBodyGlobal       `protobuf:"bytes,1,opt,name=global,proto3" json:"global"`
	ClusterTable []BltClusterSummary `protobuf:"bytes,2,rep,name=cluster_table,json=clusterTable,proto3" json:"cluster_table"`
	MemberTable  []BltMemberRecord   `protobuf:"bytes,3,rep,name=member_table,json=memberTable,proto3" json:"member_table"`
}

func (m *BltBlockBody) Reset()         { *m = BltBlockBody{} }
func (m *BltBlockBody) String() string { return proto.CompactTextString(m) }
func (*BltBlockBody) ProtoMessage()    {}
func (*BltBlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfaeb864dd5fb412, []int{3}
}
func (m *BltBlockBody) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BltBlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BltBlockBody.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BltBlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BltBlockBody.Merge(m, src)
}
func (m *BltBlockBody) XXX_Size() int {
	return m.Size()
}
func (m *BltBlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BltBlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_BltBlockBody proto.InternalMessageInfo

func (m *BltBlockBody) GetGlobal() BltBodyGlobal {
	if m != nil {
		return m.Global
	}
	return BltBodyGlobal{}
}

func (m *BltBlockBody) GetClusterTable() []BltClusterSummary {
	if m != nil {
		return m.ClusterTable
	}
	return nil
}

func (m *BltBlockBody) GetMemberTable() []BltMemberRecord {
	if m != nil {
		return m.MemberTable
	}
	return nil
}

// BltDelegate maps a cluster head (satellite) to a validator address.
type BltDelegate struct {
	ClusterId        uint32 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	HeadId           uint32 `protobuf:"varint,2,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	ValidatorAddress string `protobuf:"bytes,3,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *BltDelegate) Reset()         { *m = BltDelegate{} }
func (m *BltDelegate) String() string { return proto.CompactTextString(m) }
func (*BltDelegate) ProtoMessage()    {}
func (*BltDelegate) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfaeb864dd5fb412, []int{4}
}
func (m *BltDelegate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BltDelegate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BltDelegate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BltDelegate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BltDelegate.Merge(m, src)
}
func (m *BltDelegate) XXX_Size() int {
	return m.Size()
}
func (m *BltDelegate) XXX_DiscardUnknown() {
	xxx_messageInfo_BltDelegate.DiscardUnknown(m)
}

var xxx_messageInfo_BltDelegate proto.InternalMessageInfo

func (m *BltDelegate) GetClusterId() uint32 {
	if m != nil {
		return m.ClusterId
	}
	return 0
}

func (m *BltDelegate) GetHeadId() uint32 {
	if m != nil {
		return m.HeadId
	}
	return 0
}

func (m *BltDelegate) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

// BltDelegateSet is the current round's 12 cluster heads.
type BltDelegateSet struct {
	Delegates []BltDelegate `protobuf:"bytes,1,rep,name=delegates,proto3" json:"delegates"`
}

func (m *BltDelegateSet) Reset()         { *m = BltDelegateSet{} }
func (m *BltDelegateSet) String() string { return proto.CompactTextString(m) }
func (*BltDelegateSet) ProtoMessage()    {}
func (*BltDelegateSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfaeb864dd5fb412, []int{5}
}
func (m *BltDelegateSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BltDelegateSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BltDelegateSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BltDelegateSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BltDelegateSet.Merge(m, src)
}
func (m *BltDelegateSet) XXX_Size() int {
	return m.Size()
}
func (m *BltDelegateSet) XXX_DiscardUnknown() {
	xxx_messageInfo_BltDelegateSet.DiscardUnknown(m)
}

var xxx_messageInfo_BltDelegateSet proto.InternalMessageInfo

func (m *BltDelegateSet) GetDelegates() []BltDelegate {
	if m != nil {
		return m.Delegates
	}
	return nil
}

// BltEpochSnapshot is the persisted finalized body for an epoch.
type BltEpochSnapshot struct {
	EpochId       uint32       `protobuf:"varint,1,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Height        int64        `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Proposer      string       `protobuf:"bytes,3,opt,name=proposer,proto3" json:"proposer,omitempty"`
	RelayPathHash []byte       `protobuf:"bytes,4,opt,name=relay_path_hash,json=relayPathHash,proto3" json:"relay_path_hash,omitempty"`
	Body          BltBlockBody `protobuf:"bytes,5,opt,name=body,proto3" json:"body"`
}

func (m *BltEpochSnapshot) Reset()         { *m = BltEpochSnapshot{} }
func (m *BltEpochSnapshot) String() string { return proto.CompactTextString(m) }
func (*BltEpochSnapshot) ProtoMessage()    {}
func (*BltEpochSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfaeb864dd5fb412, []int{6}
}
func (m *BltEpochSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BltEpochSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BltEpochSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BltEpochSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BltEpochSnapshot.Merge(m, src)
}
func (m *BltEpochSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *BltEpochSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_BltEpochSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_BltEpochSnapshot proto.InternalMessageInfo

func (m *BltEpochSnapshot) GetEpochId() uint32 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *BltEpochSnapshot) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BltEpochSnapshot) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *BltEpochSnapshot) GetRelayPathHash() []byte {
	if m != nil {
		return m.RelayPathHash
	}
	return nil
}

func (m *BltEpochSnapshot) GetBody() BltBlockBody {
	if m != nil {
		return m.Body
	}
	return BltBlockBody{}
}

func init() {
	proto.RegisterType((*BltBodyGlobal)(nil), "leochain.blt.BltBodyGlobal")
	proto.RegisterType((*BltClusterSummary)(nil), "leochain.blt.BltClusterSummary")
	proto.RegisterType((*BltMemberRecord)(nil), "leochain.blt.BltMemberRecord")
	proto.RegisterType((*BltBlockBody)(nil), "leochain.blt.BltBlockBody")
	proto.RegisterType((*BltDelegate)(nil), "leochain.blt.BltDelegate")
	proto.RegisterType((*BltDelegateSet)(nil), "leochain.blt.BltDelegateSet")
	proto.RegisterType((*BltEpochSnapshot)(nil), "leochain.blt.BltEpochSnapshot")
}

func init() { proto.RegisterFile("leochain/blt/types.proto", fileDescriptor_cfaeb864dd5fb412) }

var fileDescriptor_cfaeb864dd5fb412 = []byte{
	// 726 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x4f, 0xdb, 0x4a,
	0x14, 0x8d, 0x93, 0x10, 0x60, 0x92, 0x00, 0x19, 0x85, 0x47, 0x00, 0x11, 0x78, 0x79, 0x4f, 0x4f,
	0x48, 0x4f, 0x4a, 0x8a, 0xdb, 0xa8, 0xaa, 0xd4, 0x2e, 0x30, 0xfd, 0x20, 0x95, 0x10, 0x60, 0x50,
	0x17, 0xdd, 0x58, 0x63, 0xcf, 0x24, 0xb6, 0x3a, 0xf6, 0x98, 0xf1, 0x80, 0x9a, 0xbf, 0xd0, 0x55,
	0xff, 0x51, 0xd5, 0x1d, 0x4b, 0x96, 0x5d, 0xb4, 0x55, 0x05, 0x7f, 0xa4, 0x9a, 0x8f, 0x7c, 0x40,
	0x76, 0xdd, 0xf9, 0xde, 0x7b, 0xee, 0x99, 0x7b, 0xcf, 0x1c, 0x0f, 0x68, 0x50, 0xc2, 0x82, 0x10,
	0x45, 0x49, 0xc7, 0xa7, 0xa2, 0x23, 0x86, 0x29, 0xc9, 0xda, 0x29, 0x67, 0x82, 0xc1, 0xca, 0xa8,
	0xd2, 0xf6, 0xa9, 0xd8, 0xa8, 0x0f, 0xd8, 0x80, 0xa9, 0x42, 0x47, 0x7e, 0x69, 0x4c, 0xeb, 0x93,
	0x05, 0xaa, 0x0e, 0x15, 0x0e, 0xc3, 0xc3, 0x37, 0x94, 0xf9, 0x88, 0xc2, 0x3d, 0xb0, 0x3a, 0x50,
	0x5f, 0x1e, 0x27, 0x7d, 0x4f, 0x44, 0x31, 0xf1, 0x2e, 0x1e, 0xed, 0x25, 0x59, 0xc3, 0xda, 0xb1,
	0x76, 0x8b, 0x2e, 0xd4, 0x45, 0x97, 0xf4, 0xcf, 0xa3, 0x98, 0x9c, 0xca, 0x0a, 0xfc, 0x07, 0x54,
	0x03, 0x7a, 0x99, 0x09, 0xc2, 0xbd, 0x80, 0x5d, 0x26, 0xa2, 0x91, 0xdf, 0xb1, 0x76, 0xab, 0x6e,
	0xc5, 0x24, 0x0f, 0x64, 0x0e, 0xfe, 0x0d, 0x2a, 0x31, 0x89, 0xfd, 0x31, 0xa6, 0xa0, 0x30, 0x65,
	0x9d, 0x53, 0x90, 0xd6, 0xd7, 0x3c, 0xa8, 0x39, 0x54, 0x1c, 0xe8, 0xb6, 0xb3, 0xcb, 0x38, 0x46,
	0x7c, 0x08, 0xb7, 0x00, 0x18, 0xb1, 0x47, 0x58, 0x4d, 0x51, 0x75, 0x17, 0x4d, 0xa6, 0x87, 0xe1,
	0x1a, 0x98, 0x0f, 0x09, 0xc2, 0xb2, 0xa6, 0x8f, 0x2d, 0xc9, 0xb0, 0x87, 0xe1, 0x73, 0xb0, 0xa9,
	0x0a, 0xac, 0xdf, 0xcf, 0x88, 0xf0, 0x04, 0xf3, 0xcc, 0x5e, 0x7a, 0x1d, 0x79, 0x7e, 0xcd, 0x5d,
	0x93, 0x90, 0x63, 0x85, 0x38, 0x67, 0x5a, 0x01, 0xbd, 0xd3, 0xc3, 0x71, 0x8b, 0x33, 0xe3, 0x4a,
	0x48, 0x94, 0xd0, 0x68, 0x0c, 0x99, 0xd3, 0x10, 0x9d, 0xd3, 0x90, 0xa7, 0xa0, 0x61, 0x58, 0xcc,
	0x14, 0x31, 0x41, 0x89, 0x19, 0xa0, 0xa4, 0x06, 0x58, 0xd5, 0x75, 0x3d, 0xc2, 0x11, 0x41, 0x89,
	0x3e, 0x7e, 0xa6, 0xf1, 0x0a, 0x71, 0xdd, 0x67, 0x37, 0xe6, 0xd5, 0x39, 0xf7, 0x1a, 0xdf, 0x21,
	0xae, 0xfa, 0xec, 0xd6, 0x77, 0x0b, 0x2c, 0x3b, 0x54, 0x1c, 0xa9, 0xa2, 0x4b, 0x02, 0xc6, 0x95,
	0x44, 0x09, 0xc3, 0x64, 0x22, 0x5f, 0x49, 0x86, 0x3d, 0xfc, 0x40, 0xda, 0xfc, 0x43, 0x69, 0x3b,
	0xa0, 0x3e, 0x11, 0x4f, 0x69, 0x39, 0x2d, 0x5d, 0x8d, 0x19, 0xd9, 0x0e, 0x09, 0xc2, 0x7a, 0xea,
	0x7f, 0xc1, 0x12, 0x27, 0x59, 0xea, 0xa5, 0x9c, 0xf9, 0xde, 0x85, 0xdd, 0xed, 0x1a, 0xd9, 0x2a,
	0x32, 0x7b, 0xc2, 0x99, 0x7f, 0x6a, 0x77, 0xbb, 0x12, 0xa5, 0x6c, 0x85, 0x82, 0xc0, 0x10, 0x6a,
	0xe5, 0x2a, 0x32, 0xbb, 0x1f, 0x04, 0x9a, 0xab, 0x0e, 0xe6, 0xfa, 0x14, 0x0d, 0xb4, 0x4e, 0x55,
	0x57, 0x07, 0xad, 0x1f, 0x16, 0xa8, 0x48, 0xbf, 0x52, 0x16, 0x7c, 0x90, 0xa6, 0x85, 0xcf, 0x40,
	0x49, 0x5f, 0xab, 0x5a, 0xad, 0x6c, 0x6f, 0xb6, 0xa7, 0x5d, 0xdf, 0xbe, 0xe7, 0x6d, 0xa7, 0x78,
	0xfd, 0x73, 0x3b, 0xe7, 0x9a, 0x06, 0xf8, 0x76, 0x62, 0x5b, 0x81, 0x7c, 0x4a, 0x1a, 0xf9, 0x9d,
	0xc2, 0x6e, 0xd9, 0xde, 0x9e, 0x61, 0xb8, 0x6f, 0x48, 0xc3, 0x32, 0x72, 0xf7, 0xb9, 0x6c, 0x85,
	0xaf, 0xc7, 0x76, 0xd1, 0x54, 0x05, 0x45, 0xb5, 0x35, 0x43, 0x35, 0x7d, 0x2f, 0x86, 0xc8, 0x78,
	0x4a, 0xf1, 0xb4, 0x38, 0x28, 0x3b, 0x54, 0xbc, 0x24, 0x94, 0x0c, 0x90, 0x20, 0x7f, 0xec, 0xfd,
	0xff, 0x41, 0xed, 0x0a, 0xd1, 0x08, 0x23, 0xc1, 0xb8, 0x87, 0x30, 0xe6, 0x24, 0xd3, 0xd7, 0xb6,
	0xe8, 0xae, 0x8c, 0x0b, 0xfb, 0x3a, 0xdf, 0x3a, 0x06, 0x4b, 0x53, 0x67, 0x9e, 0x11, 0x01, 0x5f,
	0x80, 0x45, 0x6c, 0x42, 0xf9, 0xdf, 0xcb, 0x55, 0xd6, 0x67, 0x56, 0x19, 0x35, 0x98, 0x35, 0x26,
	0x1d, 0xad, 0x2f, 0x16, 0x58, 0x71, 0xa8, 0x78, 0x95, 0xb2, 0x20, 0x3c, 0x4b, 0x50, 0x9a, 0x85,
	0x4c, 0xc0, 0x75, 0xb0, 0x40, 0x64, 0x62, 0xb2, 0xc8, 0xbc, 0x8a, 0x7b, 0x18, 0xfe, 0x05, 0x4a,
	0x21, 0x89, 0x06, 0xa1, 0x7e, 0x38, 0x0a, 0xae, 0x89, 0xe0, 0x06, 0x58, 0x48, 0x39, 0x4b, 0x59,
	0x46, 0xb8, 0x19, 0x7e, 0x1c, 0xc3, 0xff, 0xc0, 0x32, 0x27, 0x14, 0x0d, 0xbd, 0x14, 0x89, 0xd0,
	0x0b, 0x51, 0x16, 0x2a, 0xaf, 0x55, 0xdc, 0xaa, 0x4a, 0x9f, 0x20, 0x11, 0x1e, 0xa2, 0x2c, 0x84,
	0x4f, 0x40, 0xd1, 0x67, 0x78, 0xa8, 0x2c, 0x56, 0xb6, 0x37, 0x66, 0xdd, 0x31, 0x72, 0x92, 0x59,
	0x43, 0xa1, 0x9d, 0xf6, 0xf5, 0x6d, 0xd3, 0xba, 0xb9, 0x6d, 0x5a, 0xbf, 0x6e, 0x9b, 0xd6, 0xe7,
	0xbb, 0x66, 0xee, 0xe6, 0xae, 0x99, 0xfb, 0x76, 0xd7, 0xcc, 0xbd, 0xaf, 0x8f, 0x9f, 0xdb, 0x8f,
	0x93, 0x07, 0xd7, 0x2f, 0xa9, 0xd7, 0xf4, 0xf1, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x86,
	0xfa, 0x8a, 0x8d, 0x05, 0x00, 0x00,
}

func (m *BltBodyGlobal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BltBodyGlobal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BltBodyGlobal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MemberCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MemberCount))
		i--
		dAtA[i] = 0x18
	}
	if m.ClusterCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ClusterCount))
		i--
		dAtA[i] = 0x10
	}
	if m.GlobalRefTimeQ01Ns != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.GlobalRefTimeQ01Ns))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BltClusterSummary) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BltClusterSummary) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BltClusterSummary) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MemberOffsetVarQ01Ns2 != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MemberOffsetVarQ01Ns2))
		i--
		dAtA[i] = 0x38
	}
	if m.MemberOffsetMeanQ01Ns != 0 {
		i = encodeVarintTypes(dAtA, i, uint64((uint32(m.MemberOffsetMeanQ01Ns)<<1)^uint32((m.MemberOffsetMeanQ01Ns>>31))))
		i--
		dAtA[i] = 0x30
	}
	if m.InlierCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.InlierCount))
		i--
		dAtA[i] = 0x28
	}
	if m.MemberCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MemberCount))
		i--
		dAtA[i] = 0x20
	}
	if m.HeadOffsetToGlobalQ01Ns != 0 {
		i = encodeVarintTypes(dAtA, i, uint64((uint32(m.HeadOffsetToGlobalQ01Ns)<<1)^uint32((m.HeadOffsetToGlobalQ01Ns>>31))))
		i--
		dAtA[i] = 0x18
	}
	if m.HeadId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.HeadId))
		i--
		dAtA[i] = 0x10
	}
	if m.ClusterId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ClusterId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BltMemberRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BltMemberRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BltMemberRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Flags != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Flags))
		i--
		dAtA[i] = 0x30
	}
	if m.TimeAccQ01Ns != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TimeAccQ01Ns))
		i--
		dAtA[i] = 0x28
	}
	if m.RespProbQ255 != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RespProbQ255))
		i--
		dAtA[i] = 0x20
	}
	if m.OffsetToHeadQ01Ns != 0 {
		i = encodeVarintTypes(dAtA, i, uint64((uint32(m.OffsetToHeadQ01Ns)<<1)^uint32((m.OffsetToHeadQ01Ns>>31))))
		i--
		dAtA[i] = 0x18
	}
	if m.ClusterId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ClusterId))
		i--
		dAtA[i] = 0x10
	}
	if m.NodeId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.NodeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BltBlockBody) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BltBlockBody) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BltBlockBody) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MemberTable) > 0 {
		for iNdEx := len(m.MemberTable) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MemberTable[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ClusterTable) > 0 {
		for iNdEx := len(m.ClusterTable) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClusterTable[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Global.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *BltDelegate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BltDelegate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BltDelegate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.HeadId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.HeadId))
		i--
		dAtA[i] = 0x10
	}
	if m.ClusterId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ClusterId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BltDelegateSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BltDelegateSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BltDelegateSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Delegates) > 0 {
		for iNdEx := len(m.Delegates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Delegates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *BltEpochSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BltEpochSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BltEpochSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Body.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.RelayPathHash) > 0 {
		i -= len(m.RelayPathHash)
		copy(dAtA[i:], m.RelayPathHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RelayPathHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if m.EpochId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.EpochId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BltBodyGlobal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GlobalRefTimeQ01Ns != 0 {
		n += 1 + sovTypes(uint64(m.GlobalRefTimeQ01Ns))
	}
	if m.ClusterCount != 0 {
		n += 1 + sovTypes(uint64(m.ClusterCount))
	}
	if m.MemberCount != 0 {
		n += 1 + sovTypes(uint64(m.MemberCount))
	}
	return n
}

func (m *BltClusterSummary) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterId != 0 {
		n += 1 + sovTypes(uint64(m.ClusterId))
	}
	if m.HeadId != 0 {
		n += 1 + sovTypes(uint64(m.HeadId))
	}
	if m.HeadOffsetToGlobalQ01Ns != 0 {
		n += 1 + sozTypes(uint64(m.HeadOffsetToGlobalQ01Ns))
	}
	if m.MemberCount != 0 {
		n += 1 + sovTypes(uint64(m.MemberCount))
	}
	if m.InlierCount != 0 {
		n += 1 + sovTypes(uint64(m.InlierCount))
	}
	if m.MemberOffsetMeanQ01Ns != 0 {
		n += 1 + sozTypes(uint64(m.MemberOffsetMeanQ01Ns))
	}
	if m.MemberOffsetVarQ01Ns2 != 0 {
		n += 1 + sovTypes(uint64(m.MemberOffsetVarQ01Ns2))
	}
	return n
}

func (m *BltMemberRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NodeId != 0 {
		n += 1 + sovTypes(uint64(m.NodeId))
	}
	if m.ClusterId != 0 {
		n += 1 + sovTypes(uint64(m.ClusterId))
	}
	if m.OffsetToHeadQ01Ns != 0 {
		n += 1 + sozTypes(uint64(m.OffsetToHeadQ01Ns))
	}
	if m.RespProbQ255 != 0 {
		n += 1 + sovTypes(uint64(m.RespProbQ255))
	}
	if m.TimeAccQ01Ns != 0 {
		n += 1 + sovTypes(uint64(m.TimeAccQ01Ns))
	}
	if m.Flags != 0 {
		n += 1 + sovTypes(uint64(m.Flags))
	}
	return n
}

func (m *BltBlockBody) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Global.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.ClusterTable) > 0 {
		for _, e := range m.ClusterTable {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.MemberTable) > 0 {
		for _, e := range m.MemberTable {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *BltDelegate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterId != 0 {
		n += 1 + sovTypes(uint64(m.ClusterId))
	}
	if m.HeadId != 0 {
		n += 1 + sovTypes(uint64(m.HeadId))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *BltDelegateSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Delegates) > 0 {
		for _, e := range m.Delegates {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *BltEpochSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochId != 0 {
		n += 1 + sovTypes(uint64(m.EpochId))
	}
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.RelayPathHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.Body.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BltBodyGlobal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BltBodyGlobal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BltBodyGlobal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalRefTimeQ01Ns", wireType)
			}
			m.GlobalRefTimeQ01Ns = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GlobalRefTimeQ01Ns |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterCount", wireType)
			}
			m.ClusterCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberCount", wireType)
			}
			m.MemberCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemberCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BltClusterSummary) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BltClusterSummary: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BltClusterSummary: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterId", wireType)
			}
			m.ClusterId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeadId", wireType)
			}
			m.HeadId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HeadId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeadOffsetToGlobalQ01Ns", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.HeadOffsetToGlobalQ01Ns = v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberCount", wireType)
			}
			m.MemberCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemberCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InlierCount", wireType)
			}
			m.InlierCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InlierCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberOffsetMeanQ01Ns", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.MemberOffsetMeanQ01Ns = v
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberOffsetVarQ01Ns2", wireType)
			}
			m.MemberOffsetVarQ01Ns2 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemberOffsetVarQ01Ns2 |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BltMemberRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BltMemberRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BltMemberRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			m.NodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterId", wireType)
			}
			m.ClusterId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OffsetToHeadQ01Ns", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.OffsetToHeadQ01Ns = v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RespProbQ255", wireType)
			}
			m.RespProbQ255 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RespProbQ255 |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeAccQ01Ns", wireType)
			}
			m.TimeAccQ01Ns = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeAccQ01Ns |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			m.Flags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Flags |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BltBlockBody) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BltBlockBody: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BltBlockBody: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Global", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Global.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterTable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterTable = append(m.ClusterTable, BltClusterSummary{})
			if err := m.ClusterTable[len(m.ClusterTable)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberTable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemberTable = append(m.MemberTable, BltMemberRecord{})
			if err := m.MemberTable[len(m.MemberTable)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BltDelegate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BltDelegate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BltDelegate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterId", wireType)
			}
			m.ClusterId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeadId", wireType)
			}
			m.HeadId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HeadId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BltDelegateSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BltDelegateSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BltDelegateSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegates = append(m.Delegates, BltDelegate{})
			if err := m.Delegates[len(m.Delegates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BltEpochSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BltEpochSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BltEpochSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochId", wireType)
			}
			m.EpochId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayPathHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayPathHash = append(m.RelayPathHash[:0], dAtA[iNdEx:postIndex]...)
			if m.RelayPathHash == nil {
				m.RelayPathHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Body.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
