// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: leochain/blt/query.proto

package blt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName       = "/leochain.blt.Query/Params"
	Query_LatestEpoch_FullMethodName  = "/leochain.blt.Query/LatestEpoch"
	Query_EpochHistory_FullMethodName = "/leochain.blt.Query/EpochHistory"
	Query_DelegateSet_FullMethodName  = "/leochain.blt.Query/DelegateSet"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// LatestEpoch returns the most recently finalized BltEpochSnapshot.
	LatestEpoch(ctx context.Context, in *QueryLatestEpochRequest, opts ...grpc.CallOption) (*QueryLatestEpochResponse, error)
	// EpochHistory returns a single past epoch snapshot by id.
	EpochHistory(ctx context.Context, in *QueryEpochHistoryRequest, opts ...grpc.CallOption) (*QueryEpochHistoryResponse, error)
	// DelegateSet returns the active 12 cluster-head delegates.
	DelegateSet(ctx context.Context, in *QueryDelegateSetRequest, opts ...grpc.CallOption) (*QueryDelegateSetResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestEpoch(ctx context.Context, in *QueryLatestEpochRequest, opts ...grpc.CallOption) (*QueryLatestEpochResponse, error) {
	out := new(QueryLatestEpochResponse)
	err := c.cc.Invoke(ctx, Query_LatestEpoch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EpochHistory(ctx context.Context, in *QueryEpochHistoryRequest, opts ...grpc.CallOption) (*QueryEpochHistoryResponse, error) {
	out := new(QueryEpochHistoryResponse)
	err := c.cc.Invoke(ctx, Query_EpochHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DelegateSet(ctx context.Context, in *QueryDelegateSetRequest, opts ...grpc.CallOption) (*QueryDelegateSetResponse, error) {
	out := new(QueryDelegateSetResponse)
	err := c.cc.Invoke(ctx, Query_DelegateSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params returns the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// LatestEpoch returns the most recently finalized BltEpochSnapshot.
	LatestEpoch(context.Context, *QueryLatestEpochRequest) (*QueryLatestEpochResponse, error)
	// EpochHistory returns a single past epoch snapshot by id.
	EpochHistory(context.Context, *QueryEpochHistoryRequest) (*QueryEpochHistoryResponse, error)
	// DelegateSet returns the active 12 cluster-head delegates.
	DelegateSet(context.Context, *QueryDelegateSetRequest) (*QueryDelegateSetResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) LatestEpoch(context.Context, *QueryLatestEpochRequest) (*QueryLatestEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestEpoch not implemented")
}
func (UnimplementedQueryServer) EpochHistory(context.Context, *QueryEpochHistoryRequest) (*QueryEpochHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochHistory not implemented")
}
func (UnimplementedQueryServer) DelegateSet(context.Context, *QueryDelegateSetRequest) (*QueryDelegateSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegateSet not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LatestEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestEpoch(ctx, req.(*QueryLatestEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EpochHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEpochHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EpochHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EpochHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EpochHistory(ctx, req.(*QueryEpochHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DelegateSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDelegateSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DelegateSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DelegateSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DelegateSet(ctx, req.(*QueryDelegateSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leochain.blt.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "LatestEpoch",
			Handler:    _Query_LatestEpoch_Handler,
		},
		{
			MethodName: "EpochHistory",
			Handler:    _Query_EpochHistory_Handler,
		},
		{
			MethodName: "DelegateSet",
			Handler:    _Query_DelegateSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leochain/blt/query.proto",
}
